[2023-08-29 10:27:09] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:28:44] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:30:18] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:30:20] INFO Watching for file changes with StatReloader
[2023-08-29 10:30:43] WARNING Not Found: /phpmyadmin/
[2023-08-29 10:31:29] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:31:30] INFO Watching for file changes with StatReloader
[2023-08-29 10:32:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:32:55] INFO Watching for file changes with StatReloader
[2023-08-29 10:33:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:33:05] INFO Watching for file changes with StatReloader
[2023-08-29 10:34:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:34:29] INFO Watching for file changes with StatReloader
[2023-08-29 10:35:41] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:35:43] INFO Watching for file changes with StatReloader
[2023-08-29 10:35:57] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:35:59] INFO Watching for file changes with StatReloader
[2023-08-29 10:36:24] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:36:26] INFO Watching for file changes with StatReloader
[2023-08-29 10:36:31] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'productname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py", line 38, in saveproduct
    pname = request.POST['productname']
  File "I:\mydjangofirst\venv\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'productname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py", line 43, in saveproduct
    logger.dubug(e)
AttributeError: 'Logger' object has no attribute 'dubug'
[2023-08-29 10:36:55] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:36:57] INFO Watching for file changes with StatReloader
[2023-08-29 10:37:01] DEBUG 'productname'
[2023-08-29 10:37:01] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:44:37] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:44:39] INFO Watching for file changes with StatReloader
[2023-08-29 10:45:08] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:45:10] INFO Watching for file changes with StatReloader
[2023-08-29 10:45:46] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:45:47] INFO Watching for file changes with StatReloader
[2023-08-29 10:46:26] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:46:28] INFO Watching for file changes with StatReloader
[2023-08-29 10:46:44] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:46:47] INFO Watching for file changes with StatReloader
[2023-08-29 10:47:02] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:47:58] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:49:43] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:49:45] INFO Watching for file changes with StatReloader
[2023-08-29 10:49:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:49:56] INFO Watching for file changes with StatReloader
[2023-08-29 10:51:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:51:06] INFO Watching for file changes with StatReloader
[2023-08-29 10:51:13] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 10:59:13] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:59:15] INFO Watching for file changes with StatReloader
[2023-08-29 10:59:38] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:59:39] INFO Watching for file changes with StatReloader
[2023-08-29 10:59:48] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 10:59:50] INFO Watching for file changes with StatReloader
[2023-08-29 11:01:08] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:01:10] INFO Watching for file changes with StatReloader
[2023-08-29 11:01:34] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:01:36] INFO Watching for file changes with StatReloader
[2023-08-29 11:02:34] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:02:36] INFO Watching for file changes with StatReloader
[2023-08-29 11:03:10] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:03:12] INFO Watching for file changes with StatReloader
[2023-08-29 11:03:19] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:03:20] INFO Watching for file changes with StatReloader
[2023-08-29 11:03:48] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:03:50] INFO Watching for file changes with StatReloader
[2023-08-29 11:04:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:04:29] INFO Watching for file changes with StatReloader
[2023-08-29 11:04:37] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:04:39] INFO Watching for file changes with StatReloader
[2023-08-29 11:05:03] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:05:05] INFO Watching for file changes with StatReloader
[2023-08-29 11:05:31] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:05:33] INFO Watching for file changes with StatReloader
[2023-08-29 11:05:49] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 11:06:10] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:06:12] INFO Watching for file changes with StatReloader
[2023-08-29 11:07:57] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:07:58] INFO Watching for file changes with StatReloader
[2023-08-29 11:08:07] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:08:09] INFO Watching for file changes with StatReloader
[2023-08-29 11:08:13] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 11:08:29] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 11:09:19] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:09:21] INFO Watching for file changes with StatReloader
[2023-08-29 11:10:23] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:10:25] INFO Watching for file changes with StatReloader
[2023-08-29 11:10:36] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:10:38] INFO Watching for file changes with StatReloader
[2023-08-29 11:10:42] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-29 11:10:59] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:11:00] INFO Watching for file changes with StatReloader
[2023-08-29 11:11:09] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:11:10] INFO Watching for file changes with StatReloader
[2023-08-29 11:11:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:11:30] INFO Watching for file changes with StatReloader
[2023-08-29 11:11:43] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-29 11:11:45] INFO Watching for file changes with StatReloader
[2023-08-30 10:07:00] INFO Watching for file changes with StatReloader
[2023-08-30 10:10:33] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:10:35] INFO Watching for file changes with StatReloader
[2023-08-30 10:11:09] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:11:12] INFO Watching for file changes with StatReloader
[2023-08-30 10:11:22] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:11:26] INFO Watching for file changes with StatReloader
[2023-08-30 10:11:44] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:11:48] INFO Watching for file changes with StatReloader
[2023-08-30 10:13:48] WARNING Not Found: /favicon.ico
[2023-08-30 10:14:00] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:15:30] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:15:31] INFO Watching for file changes with StatReloader
[2023-08-30 10:15:34] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:15:36] INFO Watching for file changes with StatReloader
[2023-08-30 10:16:41] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\__init__.py changed, reloading.
[2023-08-30 10:16:43] INFO Watching for file changes with StatReloader
[2023-08-30 10:17:08] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:17:10] INFO Watching for file changes with StatReloader
[2023-08-30 10:17:33] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:17:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:17:56] INFO Watching for file changes with StatReloader
[2023-08-30 10:18:06] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\__init__.py changed, reloading.
[2023-08-30 10:18:09] INFO Watching for file changes with StatReloader
[2023-08-30 10:19:25] INFO Watching for file changes with StatReloader
[2023-08-30 10:19:40] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:20:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:20:30] INFO Watching for file changes with StatReloader
[2023-08-30 10:20:50] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:21:52] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:21:53] INFO Watching for file changes with StatReloader
[2023-08-30 10:22:02] WARNING Not Found: /accounts/login/
[2023-08-30 10:22:10] WARNING Not Found: /accounts/login/
[2023-08-30 10:22:31] WARNING Not Found: /accounts/login/
[2023-08-30 10:23:09] INFO Watching for file changes with StatReloader
[2023-08-30 10:23:35] WARNING Not Found: /accounts/login/
[2023-08-30 10:24:44] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:24:45] INFO Watching for file changes with StatReloader
[2023-08-30 10:29:53] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:29:54] INFO Watching for file changes with StatReloader
[2023-08-30 10:29:59] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:30:02] INFO Watching for file changes with StatReloader
[2023-08-30 10:30:24] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:32:32] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:32:34] INFO Watching for file changes with StatReloader
[2023-08-30 10:34:46] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:34:48] INFO Watching for file changes with StatReloader
[2023-08-30 10:35:02] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:35:04] INFO Watching for file changes with StatReloader
[2023-08-30 10:35:12] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:35:14] INFO Watching for file changes with StatReloader
[2023-08-30 10:35:28] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:37:49] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:40:21] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:40:23] INFO Watching for file changes with StatReloader
[2023-08-30 10:40:44] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:40:46] INFO Watching for file changes with StatReloader
[2023-08-30 10:40:56] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:40:58] INFO Watching for file changes with StatReloader
[2023-08-30 10:42:46] INFO Watching for file changes with StatReloader
[2023-08-30 10:43:07] INFO Watching for file changes with StatReloader
[2023-08-30 10:43:57] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:43:59] INFO Watching for file changes with StatReloader
[2023-08-30 10:45:11] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:45:13] INFO Watching for file changes with StatReloader
[2023-08-30 10:46:37] INFO Watching for file changes with StatReloader
[2023-08-30 10:46:54] INFO Watching for file changes with StatReloader
[2023-08-30 10:47:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:47:30] INFO Watching for file changes with StatReloader
[2023-08-30 10:47:55] ERROR Internal Server Error: /product/saveproduct/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.saveproduct didn't return an HttpResponse object. It returned None instead.
[2023-08-30 10:49:02] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-30 10:49:04] INFO Watching for file changes with StatReloader
[2023-08-30 10:49:23] INFO I:\mydjangofirst\mydjangodoc\productmanagement\models\product.py changed, reloading.
[2023-08-30 10:49:24] INFO Watching for file changes with StatReloader
[2023-08-30 10:51:27] INFO Watching for file changes with StatReloader
[2023-08-30 11:10:43] INFO Watching for file changes with StatReloader
[2023-08-31 10:32:49] INFO Watching for file changes with StatReloader
[2023-08-31 10:35:57] INFO Watching for file changes with StatReloader
[2023-08-31 10:36:24] WARNING Not Found: /favicon.ico
[2023-08-31 10:38:35] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:38:37] INFO Watching for file changes with StatReloader
[2023-08-31 10:39:11] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:39:13] INFO Watching for file changes with StatReloader
[2023-08-31 10:39:39] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:39:41] INFO Watching for file changes with StatReloader
[2023-08-31 10:42:15] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:42:16] INFO Watching for file changes with StatReloader
[2023-08-31 10:44:33] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:44:34] INFO Watching for file changes with StatReloader
[2023-08-31 10:45:15] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:45:17] INFO Watching for file changes with StatReloader
[2023-08-31 10:45:27] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:45:29] INFO Watching for file changes with StatReloader
[2023-08-31 10:46:37] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:46:39] INFO Watching for file changes with StatReloader
[2023-08-31 10:46:43] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:46:45] INFO Watching for file changes with StatReloader
[2023-08-31 10:47:34] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:47:35] INFO Watching for file changes with StatReloader
[2023-08-31 10:48:00] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:48:01] INFO Watching for file changes with StatReloader
[2023-08-31 10:48:08] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 10:48:11] INFO Watching for file changes with StatReloader
[2023-08-31 11:02:26] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-08-31 11:02:30] INFO Watching for file changes with StatReloader
[2023-09-01 08:40:26] INFO Watching for file changes with StatReloader
[2023-09-01 08:43:22] WARNING Not Found: /favicon.ico
[2023-09-04 10:05:42] INFO Watching for file changes with StatReloader
[2023-09-04 10:07:59] INFO Watching for file changes with StatReloader
[2023-09-04 10:17:07] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-04 10:17:09] INFO Watching for file changes with StatReloader
[2023-09-04 10:17:34] WARNING Not Found: /favicon.ico
[2023-09-04 10:17:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-04 10:17:56] INFO Watching for file changes with StatReloader
[2023-09-04 10:18:30] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-04 10:18:32] INFO Watching for file changes with StatReloader
[2023-09-04 10:19:56] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-04 10:19:58] INFO Watching for file changes with StatReloader
[2023-09-04 10:20:10] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-04 10:20:12] INFO Watching for file changes with StatReloader
[2023-09-05 09:06:34] INFO Watching for file changes with StatReloader
[2023-09-05 09:07:04] WARNING Not Found: /favicon.ico
[2023-09-05 10:04:35] INFO Watching for file changes with StatReloader
[2023-09-05 10:04:52] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-05 10:13:10] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:13:13] INFO Watching for file changes with StatReloader
[2023-09-05 10:13:14] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-05 10:13:42] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:13:44] INFO Watching for file changes with StatReloader
[2023-09-05 10:16:24] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-05 10:16:36] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:16:38] INFO Watching for file changes with StatReloader
[2023-09-05 10:50:03] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:50:17] INFO Watching for file changes with StatReloader
[2023-09-05 10:50:20] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-05 10:50:51] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:50:55] INFO Watching for file changes with StatReloader
[2023-09-05 10:52:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:52:31] INFO Watching for file changes with StatReloader
[2023-09-05 10:53:02] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:53:05] INFO Watching for file changes with StatReloader
[2023-09-05 10:53:41] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-05 10:53:44] INFO Watching for file changes with StatReloader
[2023-09-06 08:45:36] INFO Watching for file changes with StatReloader
[2023-09-06 08:45:57] WARNING Not Found: /favicon.ico
[2023-09-06 08:46:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:46:32] INFO Watching for file changes with StatReloader
[2023-09-06 08:46:37] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:46:40] INFO Watching for file changes with StatReloader
[2023-09-06 08:46:58] INFO Watching for file changes with StatReloader
[2023-09-06 08:49:00] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:49:06] INFO Watching for file changes with StatReloader
[2023-09-06 08:50:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:50:06] INFO Watching for file changes with StatReloader
[2023-09-06 08:50:11] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:50:13] INFO Watching for file changes with StatReloader
[2023-09-06 08:51:17] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:51:19] INFO Watching for file changes with StatReloader
[2023-09-06 08:53:43] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:53:45] INFO Watching for file changes with StatReloader
[2023-09-06 08:58:16] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 08:58:17] INFO Watching for file changes with StatReloader
[2023-09-06 09:00:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:00:56] INFO Watching for file changes with StatReloader
[2023-09-06 09:01:07] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:01:09] INFO Watching for file changes with StatReloader
[2023-09-06 09:03:45] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:03:47] INFO Watching for file changes with StatReloader
[2023-09-06 09:05:32] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:05:34] INFO Watching for file changes with StatReloader
[2023-09-06 09:06:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:06:06] INFO Watching for file changes with StatReloader
[2023-09-06 09:06:12] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-06 09:06:45] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:06:46] INFO Watching for file changes with StatReloader
[2023-09-06 09:06:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:06:55] INFO Watching for file changes with StatReloader
[2023-09-06 09:07:10] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:07:11] INFO Watching for file changes with StatReloader
[2023-09-06 09:11:58] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:12:00] INFO Watching for file changes with StatReloader
[2023-09-06 09:12:03] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-06 09:17:45] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:17:47] INFO Watching for file changes with StatReloader
[2023-09-06 09:17:52] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-06 09:18:05] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:18:07] INFO Watching for file changes with StatReloader
[2023-09-06 09:18:12] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-06 09:18:27] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:18:29] INFO Watching for file changes with StatReloader
[2023-09-06 09:18:31] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-06 09:19:08] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-06 09:19:10] INFO Watching for file changes with StatReloader
[2023-09-06 09:19:27] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:29:58] INFO Watching for file changes with StatReloader
[2023-09-07 09:30:36] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:30:39] WARNING Not Found: /favicon.ico
[2023-09-07 09:30:42] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:31:01] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:31:04] INFO Watching for file changes with StatReloader
[2023-09-07 09:31:12] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:32:02] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:32:05] INFO Watching for file changes with StatReloader
[2023-09-07 09:33:04] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:33:24] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:33:28] INFO Watching for file changes with StatReloader
[2023-09-07 09:33:31] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:35:57] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:36:09] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:36:13] INFO Watching for file changes with StatReloader
[2023-09-07 09:44:16] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:44:20] INFO Watching for file changes with StatReloader
[2023-09-07 09:44:24] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:44:28] INFO Watching for file changes with StatReloader
[2023-09-07 09:46:53] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:46:58] INFO Watching for file changes with StatReloader
[2023-09-07 09:47:22] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:47:27] INFO Watching for file changes with StatReloader
[2023-09-07 09:48:31] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:48:35] INFO Watching for file changes with StatReloader
[2023-09-07 09:48:44] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-07 09:49:54] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:49:59] INFO Watching for file changes with StatReloader
[2023-09-07 09:50:51] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:50:56] INFO Watching for file changes with StatReloader
[2023-09-07 09:55:19] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:55:22] INFO Watching for file changes with StatReloader
[2023-09-07 09:58:21] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:58:26] INFO Watching for file changes with StatReloader
[2023-09-07 09:58:50] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 09:58:53] INFO Watching for file changes with StatReloader
[2023-09-07 09:59:57] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:00:01] INFO Watching for file changes with StatReloader
[2023-09-07 10:00:55] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:00:59] INFO Watching for file changes with StatReloader
[2023-09-07 10:14:01] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:14:05] INFO Watching for file changes with StatReloader
[2023-09-07 10:17:34] INFO Watching for file changes with StatReloader
[2023-09-07 10:22:14] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:22:19] INFO Watching for file changes with StatReloader
[2023-09-07 10:22:30] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:22:36] INFO Watching for file changes with StatReloader
[2023-09-07 10:22:45] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:22:50] INFO Watching for file changes with StatReloader
[2023-09-07 10:23:30] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:23:34] INFO Watching for file changes with StatReloader
[2023-09-07 10:25:59] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:26:04] INFO Watching for file changes with StatReloader
[2023-09-07 10:27:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-07 10:27:09] INFO Watching for file changes with StatReloader
[2023-09-21 09:15:48] INFO Watching for file changes with StatReloader
[2023-09-21 09:17:42] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 09:17:44] INFO Watching for file changes with StatReloader
[2023-09-21 09:18:34] WARNING Not Found: /favicon.ico
[2023-09-21 09:20:46] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 09:20:48] INFO Watching for file changes with StatReloader
[2023-09-21 09:21:01] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 09:22:05] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 09:22:06] INFO Watching for file changes with StatReloader
[2023-09-21 09:22:15] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 09:22:16] INFO Watching for file changes with StatReloader
[2023-09-21 09:22:21] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:29:03] INFO Watching for file changes with StatReloader
[2023-09-21 10:29:11] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:29:40] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:29:42] INFO Watching for file changes with StatReloader
[2023-09-21 10:29:46] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:29:48] INFO Watching for file changes with StatReloader
[2023-09-21 10:29:50] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:30:49] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:30:51] INFO Watching for file changes with StatReloader
[2023-09-21 10:30:57] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:32:00] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:32:02] INFO Watching for file changes with StatReloader
[2023-09-21 10:32:20] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:32:22] INFO Watching for file changes with StatReloader
[2023-09-21 10:33:19] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:33:21] INFO Watching for file changes with StatReloader
[2023-09-21 10:33:28] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:34:00] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:34:03] INFO Watching for file changes with StatReloader
[2023-09-21 10:37:28] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:37:30] INFO Watching for file changes with StatReloader
[2023-09-21 10:39:21] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:39:23] INFO Watching for file changes with StatReloader
[2023-09-21 10:39:33] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:39:35] INFO Watching for file changes with StatReloader
[2023-09-21 10:39:43] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:40:16] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:40:18] INFO Watching for file changes with StatReloader
[2023-09-21 10:41:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:41:05] INFO Watching for file changes with StatReloader
[2023-09-21 10:41:09] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:41:11] INFO Watching for file changes with StatReloader
[2023-09-21 10:41:16] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:42:16] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:42:18] INFO Watching for file changes with StatReloader
[2023-09-21 10:43:07] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:43:09] INFO Watching for file changes with StatReloader
[2023-09-21 10:46:04] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:46:07] INFO Watching for file changes with StatReloader
[2023-09-21 10:46:19] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 10:46:43] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:46:46] INFO Watching for file changes with StatReloader
[2023-09-21 10:47:26] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:47:29] INFO Watching for file changes with StatReloader
[2023-09-21 10:51:34] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 10:51:36] INFO Watching for file changes with StatReloader
[2023-09-21 11:07:09] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:09:20] INFO Watching for file changes with StatReloader
[2023-09-21 11:12:25] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:12:27] INFO Watching for file changes with StatReloader
[2023-09-21 11:12:30] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:12:33] INFO Watching for file changes with StatReloader
[2023-09-21 11:12:40] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 11:14:12] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:14:14] INFO Watching for file changes with StatReloader
[2023-09-21 11:14:39] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:14:43] INFO Watching for file changes with StatReloader
[2023-09-21 11:14:44] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 11:16:15] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:16:17] INFO Watching for file changes with StatReloader
[2023-09-21 11:16:29] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-21 11:17:26] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-21 11:17:28] INFO Watching for file changes with StatReloader
[2023-09-21 11:17:37] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-26 10:18:05] INFO Watching for file changes with StatReloader
[2023-09-26 10:18:56] INFO Watching for file changes with StatReloader
[2023-09-26 11:03:30] INFO Watching for file changes with StatReloader
[2023-09-26 11:03:45] WARNING Not Found: /favicon.ico
[2023-09-26 11:04:07] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-26 11:04:09] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-26 11:04:22] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-26 11:04:55] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-26 11:04:59] INFO Watching for file changes with StatReloader
[2023-09-26 11:05:06] ERROR Internal Server Error: /product/product-list/
Traceback (most recent call last):
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "I:\mydjangofirst\venv\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view productmanagement.views.product.product_list didn't return an HttpResponse object. It returned None instead.
[2023-09-26 11:05:24] INFO I:\mydjangofirst\mydjangodoc\productmanagement\views\product.py changed, reloading.
[2023-09-26 11:05:26] INFO Watching for file changes with StatReloader
